name: Build project

# lOOK INTO ADDING RELEASE DRAFTER action
on:
  push:
    branches:
      - main
      - develop
      - v5
  pull_request:
    branches:
      - main
      - develop
      - v5
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'

      - name: Set the release version
        run: echo "TAGGED_VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
        shell: bash
        if: steps.version.outputs.is_valid == 'true' && github.event_name == 'release'
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '6.x'

#      - name: Setup VSTest
#        uses: darenm/Setup-VSTest@v1
#
#
#      - name: Install NPM
#        uses: actions/setup-node@v1
#        with:
#          node-version: '12'
#      - run: npm install -g azurite
#
#      - name: Start Azurite Blob Emulator
#        shell: cmd
#        run: start /B azurite-blob
        
#      - name: Install Azurite
#        id: azuright
#        uses: potatoqualitee/azuright@v1.1
#        with:
#          self-signed-cert: true
#        
        
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

#      - name: Restore Packages
#        run: dotnet restore ImageResizer.sln

      - name: Build Solution
        run: 
          dotnet build -c Release ImageResizer.sln

      - name: Test Solution (except azure)
        run: dotnet test  -c Release  --filter "FullyQualifiedName!~Azure" ImageResizer.sln

      - name: Pack
        run: dotnet pack ImageResizer.sln -c Release
        
#https://github.com/dotnet/sdk/issues/27320
      
      - name: Add Github Nuget source
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"
        
      - name: Publish nuget packages to GitHub packages
        if: steps.version.outputs.is_valid == 'true' && github.event_name == 'release'
        run: |
          dotnet nuget push bin/Release/net472/ImageResizer.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"
          dotnet nuget push bin/Release/net472/ImageResizer.Storage.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"
          dotnet nuget push bin/Release/net472/ImageResizer.Plugins.AzureReader2.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"
          dotnet nuget push bin/Release/net472/ImageResizer.Plugins.Imageflow --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"
          dotnet nuget push bin/Release/net472/ImageResizer.Plugins.HybridCache --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"
          dotnet nuget push bin/Release/net472/ImageResizer.Plugins.S3Reader2 --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"

